fieldLayouts:
  5a9e96c2-60a9-4705-a76b-9a7d5a30dc98:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d9e4f4d3-840f-4dae-a94b-7268c7d230f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d72b4db3-3c8c-4fca-8e93-3f0b35219c67 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8e5206a-d23e-4aa5-bbe0-4e76bc90afea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 043af39a-7e83-477f-b86d-01628fe60102
        userCondition: null
fs: upload
handle: upload
name: Upload
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
