defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  a13308ca-4fb7-4172-b3dd-ef36281325c9: # Bikers
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
